<a href="https://colab.research.google.com/github/lavanyagowda1998/internship/blob/master/intruduction_to_phython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
a= np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
np.__version__

'1.16.4'

In [6]:
a.shape

(2, 5)

In [7]:
a.ndim

2

In [9]:
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size

10

In [12]:
type(a)

numpy.ndarray

In [14]:
b=np.array([6,7,8])
b

array([6, 7, 8])