<a href="https://colab.research.google.com/github/lavanyagowda1998/internship/blob/master/intruduction_to_phython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a = np.arange(15).reshape(1,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [0]:
a= np.arange(20).reshape(2,2,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [0]:
np.__version__

'1.16.4'

In [0]:
a.shape

(2, 5)

In [0]:
a.ndim

3

In [0]:
a.dtype.name

'int64'

In [0]:
a.itemsize

8

In [0]:
a.size

10

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([6,7,8])
b

array([6, 7, 8])

dtype('float64')

In [0]:
b=np.array([9.0,7.0,8.0])
b

array([9., 7., 8.])

In [0]:
type(b)

numpy.ndarray

In [0]:
b.dtype

dtype('float64')

In [0]:
a=np.array([11,12,13])
a

array([11, 12, 13])

In [0]:
a=np.array([(21,22,23),(4,5,6)])
a

array([[21, 22, 23],
       [ 4,  5,  6]])

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [0]:
np.ones((2,3,4),dtype=np.float16)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)

In [0]:
np.zeros((3,3,4),dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [0]:
np.ones((3,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [0]:
np.empty((2,3))

array([[1.10008428e-19, 1.10008428e-19, 1.10008428e-19],
       [1.10008428e-19, 1.10008428e-19, 1.10008428e-19]])

In [0]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [0]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [0]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [0]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [0]:
c =np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [0]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [0]:
print(np.arange(2500).reshape(50,50))

[[   0    1    2 ...   47   48   49]
 [  50   51   52 ...   97   98   99]
 [ 100  101  102 ...  147  148  149]
 ...
 [2350 2351 2352 ... 2397 2398 2399]
 [2400 2401 2402 ... 2447 2448 2449]
 [2450 2451 2452 ... 2497 2498 2499]]


In [0]:
a=np.array([20,30,40,50])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [0]:
c=a-b
c

array([20, 29, 38, 47])

In [0]:
b**2

array([0, 1, 4, 9])

In [0]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [0]:
a<35

array([ True,  True, False, False])

In [0]:
A=np.array([[3,1,1],[2,0,0]])
B=np.array([[1,1,0],[2,2,0],[2,3,4]])
A * B

ValueError: ignored

In [0]:
print(A)

[[3 1 1]
 [2 0 0]]


In [0]:
 A @ B

array([[7, 8, 4],
       [2, 2, 0]])

In [0]:
A.dot(B)

array([[7, 8, 4],
       [2, 2, 0]])

In [0]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a *=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [0]:
b += a
b

array([[6.68346223, 6.76243802, 6.53747894],
       [6.65620888, 6.54009362, 6.41098932]])

In [0]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [0]:
b.min(axis=1)

array([0, 4, 8])

In [0]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [0]:
B = np.arange(3)
B

array([0, 1, 2])

In [0]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [0]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [0]:
C = np.array([2.,-1,4.])
np.add(B,C)

array([2., 0., 6.])

In [0]:
b

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [0]:
np.sum(b)

120

In [0]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[2]

8

In [0]:
a[2:5]

array([ 8, 27, 64])

In [0]:
a[:6:2]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [0]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [0]:
for i in a:
   print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [0]:
def f(x,y):
  return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [0]:
b[2,2]

22

In [0]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [0]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [0]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [0]:
b[-2]

array([30, 31, 32, 33])

In [0]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [0]:
for column in b:
   print(column)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [0]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [0]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [0]:
c = np.array([[[0,1,2],
              [10,12,13]],
             [[100,101,102],
             [110,112,113]]])
c.shape

(2, 2, 3)

In [0]:
print(c)


[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]


In [0]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [0]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [0]:
a = np.floor(10*np.random.random((3,4)))
a

array([[2., 8., 1., 0.],
       [5., 9., 8., 2.],
       [1., 8., 2., 9.]])

In [0]:
a.ndim

2

In [0]:
print(a)

[[2. 8. 1. 0.]
 [5. 9. 8. 2.]
 [1. 8. 2. 9.]]


In [0]:
a.ravel()

array([2., 8., 1., 0., 5., 9., 8., 2., 1., 8., 2., 9.])

In [0]:
a.reshape(6,2)

array([[2., 8.],
       [1., 0.],
       [5., 9.],
       [8., 2.],
       [1., 8.],
       [2., 9.]])

In [0]:
a

array([[2., 8., 1., 0.],
       [5., 9., 8., 2.],
       [1., 8., 2., 9.]])

In [0]:
a.shape

(3, 4)

In [0]:
a.T

array([[2., 5., 1.],
       [8., 9., 8.],
       [1., 8., 2.],
       [0., 2., 9.]])

In [0]:
a.T.shape

(4, 3)

In [0]:
a.reshape(2,-2)

array([[2., 8., 1., 0., 5., 9.],
       [8., 2., 1., 8., 2., 9.]])

In [0]:
import numpy as np
a = np.floor(10*np.random.random((2,2)))
a

array([[5., 8.],
       [3., 7.]])

In [0]:
a = np.arange(12)
b = a
b is a

True

In [0]:
b.shape=3,4
a.shape

(3, 4)

In [0]:
c = a.view()
c is a

False

In [0]:
c.base is a

True

In [0]:
c.flags.owndata

False

In [0]:
c.shape = 2,6
a.shape

(3, 4)

In [0]:
c[0,4]=1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [0]:
s=a[:,1:3]
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [0]:
s[:]=10
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [0]:
d=a.copy
d

<function ndarray.copy>

In [0]:
d  is a

False

In [0]:
d.base is a

AttributeError: ignored

In [0]:
d[0,0]=9999
a

TypeError: ignored

In [0]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [0]:
i =np.array([1,1,3,8,5])
a[i]

array([ 1,  1,  9, 64, 25])

In [0]:
A= np.array(['a','b'])
A

array(['a', 'b'], dtype='<U1')

In [0]:
j = np.array([[3,4],[9,7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [0]:
sa=np.array([[[2.3,0.1,-9.1],[4,5,6]]])
sa

array([[[ 2.3,  0.1, -9.1],
        [ 4. ,  5. ,  6. ]]])

In [0]:
sa[0]

array([[ 2.3,  0.1, -9.1],
       [ 4. ,  5. ,  6. ]])

In [0]:
sa[0,1]

array([4., 5., 6.])

In [0]:
sa[0,1,2]

6.0

In [0]:
sa.ndim

3

In [0]:
p=np.array([[0,0,0],[255,0,0],[0,255,0],[0,0,255],[255,255,255]])
p

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [0]:
i=np.array([[0,1,2,0],[0,3,4,0]])
p[i]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [0]:
a=np.arange(12).reshape(3,4)
a.ndim

2

In [0]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
i=np.array([[0,1],[1,2]])
j=np.array([[2,1],[3,3]])
a[i,j]



array([[ 2,  5],
       [ 7, 11]])

In [0]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [0]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [0]:
l=[i,j]
a[l]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


array([[ 2,  5],
       [ 7, 11]])

In [0]:
s= np.array([i,j])
a[s]

IndexError: ignored

In [0]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [0]:
time=np.linspace(20,145,5)
data=np.sin(np.arange(20)).reshape(5,4)
time array([20.,51.25,82.5,113.75,146.])
time

SyntaxError: ignored

In [0]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [0]:
a[[1,3,4]]=6
a

array([0, 6, 2, 6, 6])

In [0]:
a=np.arange(5)
a[[0,0,2]]=[1,2,3]
a


array([2, 1, 3, 3, 4])

In [0]:
a=np.arange(5)
a[[0,0,2]]+=1
a

array([1, 1, 3, 3, 4])

In [0]:
a=np.arange(12).reshape(3,4)
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [0]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [0]:
a[b]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [3]:
import numpy as np
import matplotlib.pyplot as plot
def mandelbrot(h,w,maxit=20):
  y,x = np.ogrid[-1.4:1.4:h*1 j ,-2:0.8:w*1 j]
  c = x+y*1j
  z = c
  divtime = maxit + np.zeros(z.shape, dtype=int)
  for i in range(maxit):
    z = z**2 + c
    diverge = z*np.conj(z)>2**2
    div_now = diverge & (divtime==maxit)
    divtime[div_now] = i
    z[diverge] = 2
    return divtime
  plt.imshow(mandelbrot(400,400))
  plt.show()

SyntaxError: ignored

In [0]:
import numpy as np
import matplotlib.pyplot as plt
def mandelbrot(h,w,maxit=20):
  y,x = np.ogrid[-1.4:1.4:h*1j ,-2:0.8:w*1j]
  c = x+y*1j
  z = c
  divtime = maxit + np.zeros(z.shape, dtype=int)
  for i in range(maxit):
    z = z**2 + c
    diverge = z*np.conj(z)>2**2
    div_now = diverge & (divtime==maxit)
    divtime[div_now] = i
    z[diverge] = 2
    return divtime
  plt.imshow(mandelbrot(400,400))
  plt.show()

In [12]:
import numpy as np
a= np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [14]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [15]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [17]:
j=np.array([[0.0,-1.0],[1.0,0.0]])
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [18]:
j@j

array([[-1.,  0.],
       [ 0., -1.]])

In [22]:
u=np.eye(3)
u

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.trace(u)


3.0

In [31]:
y = np.array([[5.],[7.]])
np.linalg.solve(a,y)


array([[-3.],
       [ 4.]])

In [32]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [33]:
from array import *
my_array=array('i',[1,2,3,4,5])
for i in my_array:
  print(i)

1
2
3
4
5


In [34]:
my_array[1]

2

In [36]:
my_array.append(6)
my_array

array('i', [1, 2, 3, 4, 5, 6, 6])

In [37]:
my_array.insert(1,9)
my_array

array('i', [1, 9, 2, 3, 4, 5, 6, 6])

In [39]:
my_extnd_array=array('i',[10,11,12])
my_array.extend(my_extnd_array)
my_array

array('i', [1, 9, 2, 3, 4, 5, 6, 6, 10, 11, 12])

In [40]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [1, 9, 2, 3, 4, 5, 6, 6, 10, 11, 12, 11, 12, 13])

In [52]:
my_array.remove(9)
my_array

array('i', [11, 12, 11, 10, 6, 6, 5, 4, 3, 2, 1])

In [42]:
my_array.pop()

12

In [43]:
my_array

array('i', [1, 9, 2, 3, 4, 5, 6, 6, 10, 11, 12, 11])

In [44]:
my_array.index(5)

5

In [45]:
my_array.reverse()
my_array

array('i', [11, 12, 11, 10, 6, 6, 5, 4, 3, 2, 9, 1])

In [46]:
my_array.buffer_info()



(140205232453360, 12)

In [47]:
my_array.count(11)

2

In [56]:
my_char_array=array('b', [ord('g'),ord('e'),ord('e'),ord('k')])
my_char_array

array('b', [103, 101, 101, 107])

In [51]:
c = my_array.tolist()
c

[11, 12, 11, 10, 6, 6, 5, 4, 3, 2, 9, 1]

In [57]:
my_char_array.fromstring("stuff")
my_char_array

array('b', [103, 101, 101, 107, 115, 116, 117, 102, 102])