<a href="https://colab.research.google.com/github/lavanyagowda1998/internship/blob/master/intruduction_to_phython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
a = np.arange(15).reshape(1,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [30]:
a= np.arange(20).reshape(2,2,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [5]:
np.__version__

'1.16.4'

In [6]:
a.shape

(2, 5)

In [31]:
a.ndim

3

In [9]:
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size

10

In [12]:
type(a)

numpy.ndarray

In [14]:
b=np.array([6,7,8])
b

array([6, 7, 8])

dtype('float64')

In [26]:
b=np.array([9.0,7.0,8.0])
b

array([9., 7., 8.])

In [32]:
type(b)

numpy.ndarray

In [33]:
b.dtype

dtype('float64')

In [36]:
a=np.array([11,12,13])
a

array([11, 12, 13])

In [37]:
a=np.array([(21,22,23),(4,5,6)])
a

array([[21, 22, 23],
       [ 4,  5,  6]])

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [45]:
np.ones((2,3,4),dtype=np.float16)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)

In [50]:
np.zeros((3,3,4),dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [57]:
np.ones((3,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [52]:
np.empty((2,3))

array([[1.10008428e-19, 1.10008428e-19, 1.10008428e-19],
       [1.10008428e-19, 1.10008428e-19, 1.10008428e-19]])

In [53]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [54]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [58]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [65]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [66]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [69]:
c =np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [70]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [74]:
print(np.arange(2500).reshape(50,50))

[[   0    1    2 ...   47   48   49]
 [  50   51   52 ...   97   98   99]
 [ 100  101  102 ...  147  148  149]
 ...
 [2350 2351 2352 ... 2397 2398 2399]
 [2400 2401 2402 ... 2447 2448 2449]
 [2450 2451 2452 ... 2497 2498 2499]]


In [76]:
a=np.array([20,30,40,50])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [78]:
c=a-b
c

array([20, 29, 38, 47])

In [79]:
b**2

array([0, 1, 4, 9])

In [80]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [81]:
a<35

array([ True,  True, False, False])

In [148]:
A=np.array([[3,1,1],[2,0,0]])
B=np.array([[1,1,0],[2,2,0],[2,3,4]])
A * B

ValueError: ignored

In [144]:
print(A)

[[3 1 1]
 [2 0 0]]


In [149]:
 A @ B

array([[7, 8, 4],
       [2, 2, 0]])

In [150]:
A.dot(B)

array([[7, 8, 4],
       [2, 2, 0]])

In [104]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a *=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [106]:
b += a
b

array([[6.68346223, 6.76243802, 6.53747894],
       [6.65620888, 6.54009362, 6.41098932]])

In [109]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [113]:
b.min(axis=1)

array([0, 4, 8])

In [114]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [118]:
B = np.arange(3)
B

array([0, 1, 2])

In [119]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [120]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [121]:
C = np.array([2.,-1,4.])
np.add(B,C)

array([2., 0., 6.])

In [123]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [124]:
a[2]

8

In [125]:
a[2:5]

array([ 8, 27, 64])

In [127]:
a[:6:2]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [128]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [129]:
for i in a:
   print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [132]:
def f(x,y):
  return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [134]:
b[2,2]

22

In [135]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [136]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [137]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [138]:
b[-2]

array([30, 31, 32, 33])

In [140]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [141]:
for column in b:
   print(column)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [142]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [162]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [152]:
c = np.array([[[0,1,2],
              [10,12,13]],
             [[100,101,102],
             [110,112,113]]])
c.shape

(2, 2, 3)

In [153]:
print(c)


[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]


In [156]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [157]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [158]:
a = np.floor(10*np.random.random((3,4)))
a

array([[2., 8., 1., 0.],
       [5., 9., 8., 2.],
       [1., 8., 2., 9.]])

In [159]:
a.ndim

2

In [161]:
print(a)

[[2. 8. 1. 0.]
 [5. 9. 8. 2.]
 [1. 8. 2. 9.]]


In [163]:
a.ravel()

array([2., 8., 1., 0., 5., 9., 8., 2., 1., 8., 2., 9.])

In [166]:
a.reshape(6,2)

array([[2., 8.],
       [1., 0.],
       [5., 9.],
       [8., 2.],
       [1., 8.],
       [2., 9.]])

In [169]:
a

array([[2., 8., 1., 0.],
       [5., 9., 8., 2.],
       [1., 8., 2., 9.]])

In [170]:
a.shape

(3, 4)

In [167]:
a.T

array([[2., 5., 1.],
       [8., 9., 8.],
       [1., 8., 2.],
       [0., 2., 9.]])

In [168]:
a.T.shape

(4, 3)

In [175]:
a.reshape(2,-2)

array([[2., 8., 1., 0., 5., 9.],
       [8., 2., 1., 8., 2., 9.]])